#!/usr/bin/env python3
"""Repacks retained CC0 PBR source caches into the project's texture convention.
No downloads are performed; missing source files fail before conversion:

  textures/{set}_albedo.png   sRGB colour
  textures/{set}_normal.png   OpenGL (Y+) tangent-space normal map
  textures/{set}_orm.png      R = ambient occlusion, G = roughness, B = height

Retained sources live in tools/downloads/. The script also writes
textures/SOURCES.md (attribution) and Godot .import settings for every texture
in textures/ (VRAM compressed BC7, mipmapped). Run
``godot --headless --path . --import --quit-after 120 --max-fps 30`` afterwards so the imported copies exist.

Usage:
    python3 tools/import_textures.py                  # everything
    python3 tools/import_textures.py --only grass,path
    python3 tools/import_textures.py --size 2048 --res 2k
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import pathlib
import re
import sys
import zipfile

import numpy as np
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEX = ROOT / "textures"
CACHE = ROOT / "tools" / "downloads"

# Project set -> (source, asset id). All CC0.
MANIFEST: dict[str, tuple[str, str]] = {
    "grass": ("polyhaven", "leafy_grass"),
    "litter": ("polyhaven", "forest_leaves_02"),
    "mud": ("polyhaven", "mud_forest"),
    "path": ("polyhaven", "stony_dirt_path"),
    "rock": ("polyhaven", "lichen_rock"),
    "bark_oak": ("polyhaven", "jolcham_oak_bark_01"),
    "bark_pine": ("polyhaven", "pine_bark"),
    "wood": ("polyhaven", "rough_wood"),
    "canvas": ("ambientcg", "Fabric061"),
}

# Poly Haven's asset metadata, checked 2026-09-06. Keep creator credits when
# repacking or making a partial re-import; CC0 is not a reason to omit them.
AUTHORS = {
    "leafy_grass": "Charlotte Baglioni",
    "forest_leaves_02": "Rob Tuytel",
    "mud_forest": "eye-candy.xyz",
    "stony_dirt_path": "eye-candy.xyz",
    "lichen_rock": "Rico Cilliers",
    "jolcham_oak_bark_01": "Charlotte Baglioni",
    "pine_bark": "Dimitrios Savva",
    "rough_wood": "Rob Tuytel",
    "Fabric061": "ambientCG",
}


def write_sources() -> None:
    rows = []
    for name, (source, asset) in MANIFEST.items():
        provider = "Poly Haven" if source == "polyhaven" else "ambientCG"
        url = f"https://polyhaven.com/a/{asset}" if source == "polyhaven" else f"https://ambientcg.com/view?id={asset}"
        rows.append(f"| `{name}` | [{asset}]({url}) | {AUTHORS[asset]} | {provider} | [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) |")
    (TEX / "SOURCES.md").write_text(
        "# Texture sources\n\n"
        "All nine external PBR sets used in the scene are credited below, including CC0 work. "
        "`tools/import_textures.py` resizes, repacks and, where needed, colour-adjusts "
        "the maps into albedo / OpenGL normal / ORM (AO, roughness, height). "
        "Fabric061 is a procedural material from ambientCG; the Poly Haven surfaces are photoscans.\n\n"
        "| Set | Asset | Creator credit | Provider | License |\n|---|---|---|---|---|\n"
        + "\n".join(rows) + "\n\n"
        "Creator names were checked against Poly Haven's asset metadata. ambientCG "
        "requests credit to the asset and ambientCG.com. Provider license statements: "
        "[Poly Haven](https://polyhaven.com/license), [ambientCG](https://docs.ambientcg.com/license/).\n\n"
        "The leaf, needle, fern, flower and bush atlases, water normals, foam, caustics "
        "and noise maps are generated by this project's `tools/bake_textures.py`. "
        "Scene geometry is generated by the project except the photoscanned dressing models credited in "
        "`models/SOURCES.md`.\n"
    )



def fetch(url: str, dest: pathlib.Path) -> pathlib.Path:
    if dest.exists() and dest.stat().st_size > 0:
        return dest
    raise FileNotFoundError(f"Retained source missing: {dest} ({url}); no downloads are performed")


# ------------------------------------------------------------------ sources


def polyhaven_files(asset: str, res: str) -> dict[str, pathlib.Path | None]:
    info = json.loads(fetch(f"https://api.polyhaven.com/files/{asset}", CACHE / asset / "files.json").read_text())

    def pick(names: tuple[str, ...], prefer: tuple[str, ...]) -> pathlib.Path | None:
        for wanted in names:
            for key, entry in info.items():
                if key.lower() != wanted.lower() or not isinstance(entry, dict):
                    continue
                by_res = entry.get(res) or entry.get("2k") or next(iter(entry.values()))
                for ext in prefer:
                    if ext in by_res and "url" in by_res[ext]:
                        url = by_res[ext]["url"]
                        return fetch(url, CACHE / asset / url.rsplit("/", 1)[-1])
        return None

    return {
        "albedo": pick(("Diffuse", "diff", "diffuse", "Color"), ("jpg", "png")),
        "normal": pick(("nor_gl",), ("png", "jpg")),
        "rough": pick(("Rough", "roughness"), ("jpg", "png")),
        "ao": pick(("AO", "ao"), ("jpg", "png")),
        "height": pick(("Displacement", "disp", "Bump"), ("png", "jpg")),
        "arm": pick(("arm",), ("jpg", "png")),
        "url": f"https://polyhaven.com/a/{asset}",
    }


def ambientcg_files(asset: str, res: str) -> dict[str, pathlib.Path | None]:
    tag = f"{asset}_{res.upper()}-JPG"
    zip_path = fetch(f"https://ambientcg.com/get?file={tag}.zip", CACHE / asset / f"{tag}.zip")
    folder = CACHE / asset / tag
    folder.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path) as archive:
        archive.extractall(folder)

    def find(suffix: str) -> pathlib.Path | None:
        hits = sorted(folder.glob(f"*_{suffix}.*"))
        return hits[0] if hits else None

    return {
        "albedo": find("Color"),
        "normal": find("NormalGL"),
        "rough": find("Roughness"),
        "ao": find("AmbientOcclusion"),
        "height": find("Displacement"),
        "arm": None,
        "url": f"https://ambientcg.com/view?id={asset}",
    }


# ------------------------------------------------------------------ packing


def load_gray(path: pathlib.Path, size: int) -> np.ndarray:
    image = Image.open(path)
    if image.mode in ("I;16", "I;16B", "I"):
        arr = np.asarray(image).astype(np.float32) / 65535.0
    else:
        arr = np.asarray(image.convert("L")).astype(np.float32) / 255.0
    if arr.shape[0] != size or arr.shape[1] != size:
        arr = np.asarray(Image.fromarray(arr, "F").resize((size, size), Image.LANCZOS))
    return np.clip(arr, 0.0, 1.0)


def load_rgb(path: pathlib.Path, size: int) -> Image.Image:
    image = Image.open(path).convert("RGB")
    if image.size != (size, size):
        image = image.resize((size, size), Image.LANCZOS)
    return image


def normalise_height(height: np.ndarray) -> np.ndarray:
    lo, hi = np.percentile(height, [0.5, 99.5])
    if hi - lo < 1e-4:
        return np.full_like(height, 0.5)
    return np.clip((height - lo) / (hi - lo), 0.0, 1.0)


def pack_set(name: str, files: dict, size: int) -> None:
    if files["albedo"] is None or files["normal"] is None:
        raise SystemExit(f"{name}: source is missing colour or normal map ({files})")
    load_rgb(files["albedo"], size).save(TEX / f"{name}_albedo.png", optimize=True)
    load_rgb(files["normal"], size).save(TEX / f"{name}_normal.png", optimize=True)
    arm = None
    if files["arm"] is not None:
        arm = np.asarray(load_rgb(files["arm"], size)).astype(np.float32) / 255.0
    if files["ao"] is not None:
        ao = load_gray(files["ao"], size)
    elif arm is not None:
        ao = arm[..., 0]
    else:
        ao = np.ones((size, size), np.float32)
    if files["rough"] is not None:
        rough = load_gray(files["rough"], size)
    elif arm is not None:
        rough = arm[..., 1]
    else:
        rough = np.full((size, size), 0.8, np.float32)
    height = normalise_height(load_gray(files["height"], size)) if files["height"] is not None else np.full((size, size), 0.5, np.float32)
    orm = np.stack([ao, rough, height], axis=-1)
    Image.fromarray((orm * 255.0 + 0.5).astype(np.uint8), "RGB").save(TEX / f"{name}_orm.png", optimize=True)


# ------------------------------------------------------------------ godot import settings


def import_params(png: pathlib.Path) -> str:
    lossless = png.name.startswith("noise_")
    mode = 0 if lossless else 2
    return f"""compress/mode={mode}
compress/high_quality=true
compress/lossy_quality=0.7
compress/uastc_level=0
compress/rdo_quality_loss=0.0
compress/hdr_compression=1
compress/normal_map=2
compress/channel_pack=0
mipmaps/generate=true
mipmaps/limit=-1
roughness/mode=0
roughness/src_normal=""
process/channel_remap/red=0
process/channel_remap/green=1
process/channel_remap/blue=2
process/channel_remap/alpha=3
process/fix_alpha_border=true
process/premult_alpha=false
process/normal_map_invert_y=false
process/hdr_as_srgb=false
process/hdr_clamp_exposure=false
process/size_limit=0
detect_3d/compress_to=0
"""


def write_import(png: pathlib.Path) -> None:
    import_path = png.with_name(png.name + ".import")
    uid = ""
    if import_path.exists():
        match = re.search(r'^uid="([^"]+)"', import_path.read_text(), re.M)
        if match:
            uid = match.group(1)
    source = f"res://textures/{png.name}"
    digest = hashlib.md5(source.encode()).hexdigest()
    dest = f"res://.godot/imported/{png.name}-{digest}.ctex"
    uid_line = f'uid="{uid}"\n' if uid else ""
    import_path.write_text(
        "[remap]\n\n"
        'importer="texture"\n'
        'type="CompressedTexture2D"\n'
        f"{uid_line}"
        f'path="{dest}"\n'
        "metadata={\n"
        '"vram_texture": true\n'
        "}\n\n"
        "[deps]\n\n"
        f'source_file="{source}"\n'
        f'dest_files=["{dest}"]\n\n'
        "[params]\n\n" + import_params(png)
    )


# ------------------------------------------------------------------ main


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", default="", help="comma-separated set names")
    parser.add_argument("--size", type=int, default=2048)
    parser.add_argument("--res", default="2k", help="source resolution to download (1k, 2k, 4k)")
    parser.add_argument("--skip-import-files", action="store_true")
    parser.add_argument("--credits-only", action="store_true", help="refresh complete credits without downloading or changing textures")
    args = parser.parse_args()
    if args.credits_only:
        write_sources()
        return
    only = {s for s in args.only.split(",") if s}
    for name, (source, asset) in MANIFEST.items():
        if only and name not in only:
            continue
        print(f"{name}: {source} {asset}")
        files = polyhaven_files(asset, args.res) if source == "polyhaven" else ambientcg_files(asset, args.res)
        pack_set(name, files, args.size)
        print(f"  -> {name}_albedo/_normal/_orm.png")
    write_sources()
    if not args.skip_import_files:
        for png in sorted(TEX.glob("*.png")):
            write_import(png)
        print(f"wrote import settings for {len(list(TEX.glob('*.png')))} textures")


if __name__ == "__main__":
    main()
